export const mockData = [
  {
    _id: "629121b06760a89905a8e6f8",
    index: 0,
    guid: "5f493c06-6bfc-4014-91ea-785d2ec8f54b",
    isActive: false,
    balance: "$2,227.74",
    picture: "http://placehold.it/32x32",
    age: 29,
    eyeColor: "brown",
    name: "Katharine Baxter",
    gender: "female",
    company: "CAPSCREEN",
    email: "katharinebaxter@capscreen.com",
    phone: "+1 (822) 600-2309",
    address: "644 Bleecker Street, Adamstown, North Dakota, 9282",
    about:
      "Consequat proident aliquip dolore tempor culpa elit dolore labore. Duis ad ullamco enim culpa do. Irure pariatur excepteur incididunt fugiat elit deserunt velit. Magna aute nisi culpa amet Lorem ad nisi ipsum culpa proident incididunt aliquip veniam sunt. Incididunt sint reprehenderit ad in excepteur do id deserunt excepteur non esse. Velit ut laboris id qui occaecat id proident consequat Lorem irure est. Proident irure ad labore adipisicing elit mollit tempor velit laborum.\r\n",
    registered: "2021-11-24T11:01:34 +03:00",
    latitude: -63.372783,
    longitude: 146.770102,
    tags: [
      "nisi",
      "Lorem",
      "reprehenderit",
      "consectetur",
      "ut",
      "tempor",
      "dolor",
    ],
    friends: [
      {
        id: 0,
        name: "England Horton",
      },
      {
        id: 1,
        name: "Amalia Robinson",
      },
      {
        id: 2,
        name: "Tucker Grimes",
      },
    ],
    greeting: "Hello, Katharine Baxter! You have 9 unread messages.",
    favoriteFruit: "apple",
  },
  {
    _id: "629121b0d0439c13affd826c",
    index: 1,
    guid: "752ad853-a7c9-4408-8ecd-598802f88e9b",
    isActive: true,
    balance: "$1,091.78",
    picture: "http://placehold.it/32x32",
    age: 38,
    eyeColor: "blue",
    name: "Cleveland Patel",
    gender: "male",
    company: "AUSTEX",
    email: "clevelandpatel@austex.com",
    phone: "+1 (967) 423-3133",
    address: "908 Gunnison Court, Escondida, Michigan, 4304",
    about:
      "Ea laborum pariatur aute sit. Amet occaecat sint ad dolor et eu. Occaecat tempor cillum commodo dolore aliquip elit officia ex. Laboris magna nisi in esse excepteur.\r\n",
    registered: "2019-01-08T06:21:42 +02:00",
    latitude: 64.521422,
    longitude: -81.789007,
    tags: [
      "do",
      "labore",
      "voluptate",
      "aliquip",
      "irure",
      "laboris",
      "occaecat",
    ],
    friends: [
      {
        id: 0,
        name: "Curry Bennett",
      },
      {
        id: 1,
        name: "Eleanor Juarez",
      },
      {
        id: 2,
        name: "Brooks Carson",
      },
    ],
    greeting: "Hello, Cleveland Patel! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "629121b0e3d6d76b8e13ba69",
    index: 2,
    guid: "16116bec-ac74-4ab7-b548-b8b8c63a5c49",
    isActive: false,
    balance: "$1,287.06",
    picture: "http://placehold.it/32x32",
    age: 28,
    eyeColor: "blue",
    name: "Patrica Barrera",
    gender: "female",
    company: "UPDAT",
    email: "patricabarrera@updat.com",
    phone: "+1 (901) 494-3468",
    address: "264 Overbaugh Place, Bluffview, Ohio, 5574",
    about:
      "Magna voluptate ad sint commodo enim. Quis anim consectetur incididunt sint cupidatat ullamco tempor. Id fugiat ad culpa ipsum consequat proident ad nostrud laboris qui minim eiusmod. Ullamco exercitation sit nostrud veniam sint aliqua. Est aute velit duis non. Laboris eu labore eiusmod sint eu. Officia sit occaecat ex cillum occaecat laborum mollit.\r\n",
    registered: "2022-01-15T02:58:19 +03:00",
    latitude: 27.787192,
    longitude: -170.603372,
    tags: ["in", "culpa", "aliquip", "eu", "irure", "sit", "esse"],
    friends: [
      {
        id: 0,
        name: "Figueroa Oneal",
      },
      {
        id: 1,
        name: "Marla Johnston",
      },
      {
        id: 2,
        name: "Whitley Spence",
      },
    ],
    greeting: "Hello, Patrica Barrera! You have 2 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "629121b0ca7a7c0aa5f305da",
    index: 3,
    guid: "5fe5a985-b2c9-46e3-8ab9-bd54a9635031",
    isActive: true,
    balance: "$2,800.25",
    picture: "http://placehold.it/32x32",
    age: 20,
    eyeColor: "green",
    name: "Claudette Rivers",
    gender: "female",
    company: "KENGEN",
    email: "claudetterivers@kengen.com",
    phone: "+1 (916) 450-2550",
    address: "558 Boynton Place, Warsaw, Wyoming, 7753",
    about:
      "Officia esse ullamco incididunt laborum culpa aute duis occaecat. Enim dolor adipisicing reprehenderit culpa duis nulla velit. Nulla ullamco quis esse officia exercitation enim dolor. Proident minim ipsum magna proident cupidatat tempor ea reprehenderit veniam ipsum in. Veniam culpa dolore fugiat ad consectetur incididunt magna ullamco commodo laboris. Nulla exercitation duis culpa cupidatat incididunt. Aliqua qui non minim in tempor laboris reprehenderit enim.\r\n",
    registered: "2015-08-24T08:39:09 +03:00",
    latitude: 57.701863,
    longitude: 63.263024,
    tags: ["laboris", "sunt", "qui", "sint", "voluptate", "veniam", "in"],
    friends: [
      {
        id: 0,
        name: "Harvey Evans",
      },
      {
        id: 1,
        name: "Mia Nguyen",
      },
      {
        id: 2,
        name: "Dorthy Flynn",
      },
    ],
    greeting: "Hello, Claudette Rivers! You have 4 unread messages.",
    favoriteFruit: "banana",
  },
  {
    _id: "629121b0edb88d9eb6ed535f",
    index: 4,
    guid: "b1a4b1f5-339c-4e2c-968c-849bad9f60c7",
    isActive: false,
    balance: "$3,828.43",
    picture: "http://placehold.it/32x32",
    age: 26,
    eyeColor: "blue",
    name: "Margaret Blackwell",
    gender: "female",
    company: "OBONES",
    email: "margaretblackwell@obones.com",
    phone: "+1 (811) 500-3538",
    address: "207 Tompkins Avenue, Greer, South Dakota, 1015",
    about:
      "Labore incididunt eiusmod sunt enim duis veniam laboris magna excepteur aute commodo. Nostrud qui culpa aute laboris anim. Dolore nisi labore mollit ex officia nulla mollit dolore id nisi amet quis laboris. Officia proident duis elit sint elit laborum labore eiusmod veniam aliquip.\r\n",
    registered: "2017-07-23T08:33:27 +03:00",
    latitude: 4.088521,
    longitude: -60.297315,
    tags: [
      "laborum",
      "irure",
      "laborum",
      "id",
      "laboris",
      "aliqua",
      "excepteur",
    ],
    friends: [
      {
        id: 0,
        name: "Woods Wilson",
      },
      {
        id: 1,
        name: "Keisha Hunt",
      },
      {
        id: 2,
        name: "Laurie Rodriquez",
      },
    ],
    greeting: "Hello, Margaret Blackwell! You have 6 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    _id: "629121b0ee6e22580e6f521a",
    index: 5,
    guid: "c3485b70-3438-4c8b-a2ab-e377f7a670d8",
    isActive: false,
    balance: "$1,176.70",
    picture: "http://placehold.it/32x32",
    age: 38,
    eyeColor: "green",
    name: "Palmer Norton",
    gender: "male",
    company: "SURETECH",
    email: "palmernorton@suretech.com",
    phone: "+1 (854) 459-2000",
    address: "538 Alice Court, Bakersville, Virgin Islands, 7838",
    about:
      "Laborum eiusmod aliqua officia aute fugiat aliqua id sunt dolor minim adipisicing. Sunt voluptate eiusmod ad amet ad tempor ut voluptate commodo irure excepteur elit ex tempor. Exercitation ea deserunt consequat est ad occaecat ullamco dolor excepteur aliquip consectetur ad adipisicing. Mollit commodo ea fugiat commodo sit nulla deserunt non officia.\r\n",
    registered: "2022-04-25T11:25:59 +03:00",
    latitude: -58.905472,
    longitude: 153.159681,
    tags: ["amet", "laboris", "labore", "pariatur", "dolor", "enim", "elit"],
    friends: [
      {
        id: 0,
        name: "Julianne Pitts",
      },
      {
        id: 1,
        name: "Mcfarland Scott",
      },
      {
        id: 2,
        name: "Carr Sargent",
      },
    ],
    greeting: "Hello, Palmer Norton! You have 5 unread messages.",
    favoriteFruit: "banana",
  },
];
